### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ghost** [eishiya/tiled-scripts#4]
Hi

Thanks for so many extensions!
Where do they appear in Tiled?

**Comment by eishiya** [comment]
Once installed, the Actions appear in various Tiled menus. The comments at the top of each script say which menu(s) the action(s) added by the script are in. Tools appear in the Map Editor toolbar.

**Comment by ghost** [comment]
Can a script add anywhere in Tiled a menu or button?

**Comment by eishiya** [comment]
Please ask questions pertaining to Tiled in the Tiled community. The issues section here should be used for issues/questions directly related to the scripts in this repository.

But, to save you the trouble of reposting this there: You can add actions to all the menus that you can see listed if you do `tiled.menus` in the Tiled console. This isn't every menu in the program, but it's most of them. You cannot create your own menus or submenus. Tools are always added to the Map Editor toolbar, there is currently no way to add Tileset Editor tools. Tools can optionally have actions associated with them that are also shown in the Map Editor toolbar when the Tool is active.
